version: '3.8'

services:
  redis:
    container_name: "redis"
    image: "redis:alpine"
    restart: always

    command: redis-server

    ports:
      - "6379:6379"

  go:
    container_name: "url_shortener"
    build:
      context: .

    ports:
      - "3000:3000"

    depends_on:
      - redis
